language: node_js

node_js:
- '10'

sudo: false

branches:
  only:
  - master

install:
- npm i -g now
- npm install -g @quasar/cli

before_script:
- npm install

cache:
  directories:
  - node_modules
  
script:
- npm run lint
- npm run build

