language: node_js

node_js:
- '10'

sudo: false

branches:
  only:
  - master

install:
# - sudo apt install xvfb
# - npm install -g @angular/cli

before_script:
- npm install

cache:
  directories:
  - node_modules
  
script:
- npm run lint
# - npm run build
# - ng build --prod
